"""empty message

Revision ID: 1169c58dbee9
Revises: b260d8f39e56
Create Date: 2022-03-24 16:23:32.104228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1169c58dbee9'
down_revision = 'b260d8f39e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'user_id')
    )
    op.alter_column('monetary_circulation', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monetary_circulation', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
