"""empty message

Revision ID: 56b3a20ca2cd
Revises: ddc7ff379091
Create Date: 2021-11-03 14:05:13.214946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b3a20ca2cd'
down_revision = 'ddc7ff379091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monetary_circulation', sa.Column('cost_item_id', sa.Integer(), nullable=False))
    op.add_column('monetary_circulation', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('monetary_circulation', sa.Column('income_sum', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('monetary_circulation', sa.Column('spending_sum', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'monetary_circulation', 'cost_items', ['cost_item_id'], ['id'])
    op.drop_column('monetary_circulation', 'spending')
    op.drop_column('monetary_circulation', 'income')
    op.drop_column('monetary_circulation', 'notice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monetary_circulation', sa.Column('notice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monetary_circulation', sa.Column('income', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('monetary_circulation', sa.Column('spending', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monetary_circulation', type_='foreignkey')
    op.drop_column('monetary_circulation', 'spending_sum')
    op.drop_column('monetary_circulation', 'income_sum')
    op.drop_column('monetary_circulation', 'notes')
    op.drop_column('monetary_circulation', 'cost_item_id')
    # ### end Alembic commands ###
