"""empty message

Revision ID: b260d8f39e56
Revises: cd865d04dbb0
Create Date: 2021-11-17 18:42:22.346541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b260d8f39e56'
down_revision = 'cd865d04dbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('monetary_circulation', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'monetary_circulation', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monetary_circulation', type_='foreignkey')
    op.drop_column('monetary_circulation', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
