"""empty message

Revision ID: cd865d04dbb0
Revises: 56b3a20ca2cd
Create Date: 2021-11-03 14:33:00.245237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd865d04dbb0'
down_revision = '56b3a20ca2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monetary_circulation', sa.Column('date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monetary_circulation', 'date_time')
    # ### end Alembic commands ###
